import type { Metadata } from "next";
import AuthProvider from "@/context/AuthProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import './globals.css'
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans")}
    >
      <AuthProvider>
        <body className="min-h-full flex flex-col">
          <Navbar />
          {children}
          <Toaster richColors theme="light" />
        </body>
      </AuthProvider>
    </html>
  );
}
